core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('users/', include("users.urls")),
    path('users/', include('django.contrib.auth.urls')),
    path("products/", include('products.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import IndexView, CategoryView

app_name = 'main' #=> main:index
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<str:category_name>/category', CategoryView.as_view(), name='category'),
]

products/urls.py
from django.urls import path
from .views import new_product, product_detail, product_update, product_delete, new_comment, delete_comment

app_name = 'products' # {% url 'products:new' %}
urlpatterns = [
    path("new", new_product, name='new'),
    path("<int:product_id>/detail", product_detail, name='detail'),
    path("<int:product_id>/update", product_update, name='update'),
    path("<int:product_id>/delete", product_delete, name='delete'),
    path("<int:product_id>/comment/new", new_comment, name='comment_new'),
    path("<int:product_id>/comment/<int:comment_id>/delete", delete_comment, name='comment_delete'),
]

users/urls.py
from .views import SignupView, ProfileView, UpdateProfileView, AddRemoveSavedView, SavedView, RecentlyViewedView
from django.urls import path

app_name='users'
urlpatterns = [
    path('signup', SignupView.as_view(), name='signup'),
    path('profile/<str:username>', ProfileView.as_view(), name='profile'),
    path('update', UpdateProfileView.as_view(), name='update'),
    path('addremovesaved/<int:product_id>', AddRemoveSavedView.as_view(), name='addremovesaved'),
    path('saveds', SavedView.as_view(), name='saveds'),
    path('recently-viewed', RecentlyViewedView.as_view(), name='recently_viewed')
]

products/models.py
from django.db import models
from users.models import CustomUser

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name

class Product(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)    
    category = models.ForeignKey(Category, on_delete=models.CASCADE)   
    title = models.CharField(max_length=150)
    description = models.TextField()
    price =  models.DecimalField(max_digits=1000, decimal_places=2)
    address = models.CharField(max_length=150)
    phone_number = models.CharField(max_length=17)
    tg_username = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ('-id',)

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)    
    image = models.ImageField(upload_to='product_images')

    
class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)    
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)    
    body = models.CharField(max_length=150)
    date  = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return "Comment of " + str(self.author.username)
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} NuraShop {% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<style>
    img{
        object-fit: contain;
    }
</style>
<body>
    <!-- Navbar Start -->
    <nav class="shadow navbar navbar-expand-lg bg-light">
        <div class="container">
          <a class="navbar-brand" href="/">NuraShop</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-tem">
                <div class="btn-group">
                  <button type="button" class="btn  dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                    Categories
                  </button>
                  <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg">
                        {% for i in categories %}
                        <li><a class="dropdown-item" href="{% url 'main:category' i.name %}">{{i.name}}</a></li>
                        {% endfor %}
                      
                  </ul>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'products:new' %}">Add Product</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:saveds' %}">Saveds</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:recently_viewed' %}">Recently Viewed</a>
              </li>
              
              
            </ul>
              <div class="btn-group">
                <form class="d-flex " role="search">
                  <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                {% if request.user.is_authenticated %}
            
                <button type="button" class="btn  dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                  <img src="{{ request.user.avatar.url }}" width="35" height="35" class=" rounded" alt="">
                </button>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg">
                  <li><a class="dropdown-item" href="">Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
                  <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                </ul>
                {% else %}
                <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
                <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
                {% endif %}
              </div>
          </div>
        </div>
    </nav>
    <!-- Navbar End -->
   {% block content %}
     
   {% endblock content %}
  
    <div class="container">
      {% if messages %}
        <div style="z-index: 312;" class="shadow-sm position-fixed end-0 bottom-0 mt-4">
          {% for message in messages  %}
            <div style="width: 20rem; opacity:0.9 " class=" m-3 alert alert-{{message.tags}}" role="alert">
               {{message}}
            </div>
            {% endfor %}
        </div>
      {% endif %}  
    </div>  
      
    <div class="footer m-5 mb-3 ">
        <center class="text-muted" >NuraShop| 2023</center>
    </div>
    <script src="{% static 'scripts.js' %}" ></script>
    <!-- <script src="js/bootstrap.bundle.min.js"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script> -->
</body>
</html>

templates/category.html
{% extends "base.html" %}
{% block title %}
  E-Bazar - {{category}}
{% endblock title %}

{% block content %}
   <!-- Product Cart Start -->
   <div class="container">
    <div class=" w-100 mt-4">
        <h4 class="d-block" >Recently Products in {{category}}</h4>
        <div class="d-flex flex-wrap justify-content-between">
            {% for i in products %}
            <!-- Product Cart Start -->
            <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                {% if i.productimage_set.exists %}
                <img height="200" class=" card-img-top" src="{{i.productimage_set.all.first.image.url}}" alt="">
                {% else %}
                <img height="200" class=" card-img-top" src="images/14pro2.jfif" alt="">
                {% endif %}
                <div class="card-body">
                    <h6 class="align-center card-title">{{i.title}}</h6>
                    <span class="center card-text"><small>$ {{i.narx}}</small></span>
                    <div class="buttons d-flex flex-wrap justify-content-between ">
                        <i class="bi bi-bookmark-fill"></i> 
                        <a href="{% url 'products:detail' i.id %}" class="btn btn-outline-primary" >Details</a>
                    </div>
                </div>
            </div>  
            <!-- Product Cart End -->
            {% endfor %}
            
        </div>
    </div>
</div>
<!-- Product Cart End -->
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% block title %}
  E-Bazar - Home
{% endblock title %}

{% block content %}
   <!-- Product Cart Start -->
   <div class="container">
    <div class=" w-100 mt-4">
        <h4 class="d-block" >Recently Products</h4>
        <div class="d-flex flex-wrap justify-content-between">
            {% for i in products %}
            <!-- Product Cart Start -->
            <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                {% if i.productimage_set.exists %}
                <img height="200" class=" card-img-top" src="{{i.productimage_set.all.first.image.url}}" alt="">
                {% else %}
                <img height="200" class=" card-img-top" src="images/14pro2.jfif" alt="">
                {% endif %}
                <div class="card-body">
                    <h6 class="align-center card-title">{{i.title}}</h6>
                    <span class="center card-text"><small>$ {{i.price}}</small></span>
                    <div class="buttons d-flex flex-wrap justify-content-between ">
                        <a href="{% url 'users:addremovesaved' i.id %}">📥</a>
                        <a href="{% url 'products:detail' i.id %}" class="btn btn-outline-primary" >Details</a>
                    </div>
                </div>
            </div>  
            <!-- Product Cart End -->
            {% endfor %}
            
        </div>
    </div>
</div>
<!-- Product Cart End -->
{% endblock content %}

templates/product_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  Delete - {{product.title}}
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-6 mt-5 ">
            <h2>Are you sure to delete -  {{product.title}}</h2>
            <form  method="post" enctype="multipart/form-data" >{% csrf_token %}
                
                <button type="submit" class="btn btn-primary" >Submit</button>
                <a class="btn btn-secondary" href="{% url 'products:detail' product.id %}"> Back Detail</a>
            </form>
        </div>
        <div class="col"></div>
    </div>
  </div>
{% endblock content %}

templates/product_detail.html
{% extends "base.html" %}
{% block title %}
   E-Bazar - {{product.title}}
{% endblock title %}
{% block content %}
<div class="container">
    <div class=" w-100 mt-5 ">
        <div class="row shadow-sm ">
            <div class="col-4 p-3">
                <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        {% for picture in product.productimage_set.all  %}
                        {% if picture == product.productimage_set.all.first %}
                        <div class="carousel-item active thumbnail shadow-sm ">
                            <img class="d-block w-100 " width="400" height="270" src="{{picture.image.url}}" alt="">
                        </div>
                        {% else %}
                        <div class="carousel-item thumbnail shadow-sm">
                            <img class="d-block w-100  " width="400" height="270" src="{{picture.image.url}}" alt="">
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
              </div> 
            </div>
            <div class="col-7 p-5 ">
                <h4>{{product.title}}</h4>
                <p class="text-muted"><a href="{% url 'users:profile' product.author.username  %}">@{{product.author.username}}</a> | 25.01.2023</p>
                <p >{{product.description|safe}}</p>
                <div class="contact mt-4 ">
                    {% if request.user == product.author %}
                    <a class="btn btn-warning" href="{% url 'products:update' product.id %}">Edit details</a>
                    {% endif %}
                    <a class="btn btn-primary" href="mailto:{{product.author.email}}">Email</a>
                    <a class="btn btn-primary" href="tel:{{product.phone_number}}">Call</a>
                    <a class="btn btn-primary" href="http://t.me/@{{product.tg_username}}">Telegram</a>
                </div>
            </div>
        </div>
        <div class="row ">  
            <div class="col-8 mt-5" >
                <h6  >In This Category</h6> 
                <div class="d-flex flex-wrap justify-content-between">
                    {% for i in product.category.product_set.all %}
                    {% if product != i %}
                    <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 14rem;" >
                        <img height="190" class=" card-img-top" src="{{i.productimage_set.all.first.image.url}}" alt="">
                        <div class="card-body">
                            <h6 class="align-center card-title"> {{i.title}}</h6>
                            <span class="center card-text">${{i.price}}</span>
                            <div class="buttons d-flex flex-wrap justify-content-between ">
                                <i class="bi bi-bookmark-fill"></i> 
                                <a href="{% url 'products:detail' i.id %}" class="btn btn-outline-primary" >Details</a>
                            </div>
                        </div>
                    </div>
                    {% endif %}  
                    {% endfor %}
                </div>
            </div>
            <div class="col-4 mt-5 shadow-sm ">
                <h6 class="pt-2" >Add comment</h6>
                <form action="{% url 'products:comment_new' product.id %}" method="post" class="input-group"> {% csrf_token %}
                    <input class="form-control" name="body" type="text" placeholder="Type your comment..." aria-describedby="'button-addon" >
                    <button class="btn btn-outline-success" type="submit" id="button-addon">Send</button>
                </form>  
                <hr>
                <h6>Comments</h6>
                {% for comment in product.comment_set.all %}
                <small class="text-muted" >@{{comment.author}} | {{comment.date}}</small>
                <p>{{comment.body}} 
                    {% if request.user == comment.author %}
                        <small><a href="{% url 'products:comment_delete' product.id comment.id   %}">delete</a></small>  
                    {% endif %}
                     
                </p>  
                {% endfor %}
            </div>
        </div>

</div>
</div>
{% endblock content %}

templates/product_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  New Product
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-6 mt-5 ">
            <h2>New Product</h2>
            <form  method="post" enctype="multipart/form-data" >{% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary" >Submit</button>
                <a class="btn btn-secondary" href="{% url 'main:index'  %}"> Back home</a>
            </form>
        </div>
        <div class="col"></div>
    </div>
  </div>
{% endblock content %}

templates/product_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  Update Product -{{pr.title}}
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-6 mt-5 ">
            <h2>Update Product -{{pr.title}}</h2>
            <form  method="post" enctype="multipart/form-data" >{% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary" >Submit</button>
                <a class="btn btn-danger" href="{% url 'products:delete' pr.id  %}"> Delete</a>
                <a class="btn btn-secondary" href="{% url 'products:detail' pr.id  %}"> Back Detail</a>
            </form>
        </div>
        <div class="col"></div>
    </div>
  </div>
{% endblock content %}

templates/profile.html
{% extends "base.html" %}
{% block title %}
  E-Bazar - {{customuser}}
{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 card mt-5 ">
            <div class="row">
                <div class="col-2 m-3">
                    <img class="img-thumbnail" width="150" height="150" src="{{customuser.avatar.url}}" alt="profile image">
                </div>
                <div class="col-8 m-3">
                    <h2>{{customuser.get_full_name}}</h2>
                    <p class="text-muted" >@{{customuser.username}} | {{customuser.email}}</p>
                    {% if customuser == request.user %}
                    <a class="btn btn-warning" href="{% url 'users:update' %}">Edit details</a>
                    <a class="btn btn-danger" href="{% url 'password_change' %}">Update Password</a>
                    {% endif %}
                    <a class="btn btn-primary" href="mailto:{{customuser.email}}">Email</a>
                    <a class="btn btn-primary" href="tel:{{customuser.phone_number}}">Call</a>
                    <a class="btn btn-primary" href="http://t.me/@{{customuser.tg_username}}">Telegram</a>
                </div>
            </div>
        </div>
    </div>
</div>  
 <!-- Product Cart Start -->
 <div class="container">
    <div class=" w-100 mt-4">
        <h4 class="d-block" >Recently Products of @{{customuser}}</h4>
        {% if not customuser.product_set.exists %}
            <center class="text-muted" >There is no products</center>
        {% endif %}    
        <div class="d-flex flex-wrap justify-content-between">
            {% for i in customuser.product_set.all %}
            <!-- Product Cart Start -->
            <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                {% if i.productimage_set.exists %}
                <img height="200" class=" card-img-top" src="{{i.productimage_set.all.first.image.url}}" alt="">
                {% else %}
                <img height="200" class=" card-img-top" src="images/14pro2.jfif" alt="">
                {% endif %}
                <div class="card-body">
                    <h6 class="align-center card-title">{{i.title}}</h6>
                    <span class="center card-text"><small>$ {{i.price}}</small></span>
                    <div class="buttons d-flex flex-wrap justify-content-between ">
                        <i class="bi bi-bookmark-fill"></i> 
                        <a href="#" class="btn btn-outline-primary" >Details</a>
                    </div>
                </div>
            </div>  
            <!-- Product Cart End -->
            {% endfor %}
            
        </div>
    </div>
</div>
<!-- Product Cart End --> 
{% endblock content %}

templates/profile_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  Update Profile - {{request.user}}
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-6 mt-5 ">
            <h2>Update Profile - {{request.user}}</h2>
            <form  method="post" enctype="multipart/form-data" >{% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary" >Submit</button>
                <a class="btn btn-secondary" href="{% url 'users:profile' request.user %}"> Back</a>
            </form>
        </div>
        <div class="col"></div>
    </div>
  </div>
{% endblock content %}

templates/recently_viewed.html
{% extends "base.html" %}
{% block title %}
  E-Bazar - Recently Viewed
{% endblock title %}

{% block content %}
   <!-- Product Cart Start -->
   <div class="container">
    <div class=" w-100 mt-4">
        <h4 class="d-block" > Recently Viewed Products</h4>
        <div class="d-flex flex-wrap justify-content-between">
            {% for i in products %}
            <!-- Product Cart Start -->
            <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                {% if i.productimage_set.exists %}
                <img height="200" class=" card-img-top" src="{{i.productimage_set.all.first.image.url}}" alt="">
                {% else %}
                <img height="200" class=" card-img-top" src="images/14pro2.jfif" alt="">
                {% endif %}
                <div class="card-body">
                    <h6 class="align-center card-title">{{i.title}}</h6>
                    <span class="center card-text"><small>$ {{i.price}}</small></span>
                    <div class="buttons d-flex flex-wrap justify-content-between ">
                        <a href="{% url 'users:addremovesaved' i.id %}">📥</a>
                        <a href="{% url 'products:detail' i.id %}" class="btn btn-outline-primary" >Details</a>
                    </div>
                </div>
            </div>  
            <!-- Product Cart End -->
            {% endfor %}
            
        </div>
    </div>
</div>
<!-- Product Cart End -->
{% endblock content %}

templates/saveds.html
{% extends "base.html" %}
{% block title %}
  E-Bazar - Saved Products of @{{request.user}}
{% endblock title %}

{% block content %}
   <!-- Product Cart Start -->
   <div class="container">
    <div class=" w-100 mt-4">
        <h4 class="d-block" >Saved Products of @{{request.user}}</h4>
        <div class="d-flex flex-wrap justify-content-between">
            {% for i in saveds %}
            <!-- Product Cart Start -->
            <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                {% if i.product.productimage_set.exists %}
                <img height="200" class=" card-img-top" src="{{i.product.productimage_set.all.first.image.url}}" alt="">
                {% else %}
                <img height="200" class=" card-img-top" src="images/14pro2.jfif" alt="">
                {% endif %}
                <div class="card-body">
                    <h6 class="align-center card-title">{{i.product.title}}</h6>
                    <span class="center card-text"><small>$ {{i.product.price}}</small></span>
                    <div class="buttons d-flex flex-wrap justify-content-between ">
                        <i class="bi bi-bookmark-fill"></i> 
                        <a href="{% url 'products:detail' i.product.id %}" class="btn btn-outline-primary" >Details</a>
                    </div>
                </div>
            </div>  
            <!-- Product Cart End -->
            {% endfor %}
            
        </div>
    </div>
</div>
<!-- Product Cart End -->
{% endblock content %}